var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// postinstall/util/EnvGenerator.ts
import { writeFileSync as writeFileSync3, readFileSync as readFileSync2, existsSync as existsSync2, rmSync } from "fs";

// postinstall/util/FileManager.ts
import path from "path";
import { existsSync, appendFileSync, writeFileSync as writeFileSync2, mkdirSync, readFileSync } from "fs";
import { parse as parseJsonc, modify, applyEdits } from "jsonc-parser";

// postinstall/util/runtimeStub.ts
import { writeFileSync } from "fs";
var RUNTIME_STUB_CONTENT = [
  "// Generated by @dxfrontier/cds-ts-dispatcher \u2014 runtime stub for the '#dispatcher' import alias.",
  "// All exports are TypeScript types; see index.ts.",
  ""
].join("\n");
function writeRuntimeStub(filePath) {
  writeFileSync(filePath, RUNTIME_STUB_CONTENT);
}
__name(writeRuntimeStub, "writeRuntimeStub");

// postinstall/util/FileManager.ts
import fg from "fast-glob";
var FileManager = class _FileManager {
  static {
    __name(this, "FileManager");
  }
  // `INIT_CWD` is the directory `npm`/`yarn`/`pnpm` was invoked from. It is absent when the
  // postinstall is re-run by hand or through flows like pnpm's `approve-builds`, so fall back to the
  // current working directory instead of blowing up on `undefined`.
  currentInstallDirectory = process.env.INIT_CWD ?? process.cwd();
  dispatcherNecessaryFiles = {
    packageJson: "package.json",
    folder: "@dispatcher",
    env: "index.ts",
    runtimeStub: "index.js",
    gitIgnore: ".gitignore",
    tsConfig: "tsconfig.json"
  };
  dispatcherExecutionPath = {
    paths: []
  };
  constructor() {
    this.run();
  }
  static joinPaths(...paths) {
    return path.join(...paths);
  }
  readPackageJson(filePath) {
    return JSON.parse(readFileSync(filePath, "utf8"));
  }
  getRootPackageJson() {
    const path2 = _FileManager.joinPaths(this.currentInstallDirectory, this.dispatcherNecessaryFiles.packageJson);
    const packageJson = this.readPackageJson(path2);
    return {
      hasWorkspaces: /* @__PURE__ */ __name(() => (packageJson.workspaces?.length ?? 0) > 0, "hasWorkspaces"),
      getWorkspaces: /* @__PURE__ */ __name(() => packageJson.workspaces, "getWorkspaces"),
      isDispatcherItself: /* @__PURE__ */ __name(() => packageJson.name === "@dxfrontier/cds-ts-dispatcher", "isDispatcherItself")
    };
  }
  isWorkspaceDynamicPattern(workspace) {
    return fg.isDynamicPattern(workspace) ? true : false;
  }
  getParsedPackageJson(workspace) {
    const sanitizedWorkspace = workspace.replace("*", "");
    const path2 = _FileManager.joinPaths(this.currentInstallDirectory, sanitizedWorkspace);
    const resolveRoot = /* @__PURE__ */ __name(() => {
      return _FileManager.joinPaths(this.currentInstallDirectory, this.dispatcherNecessaryFiles.packageJson);
    }, "resolveRoot");
    const resolveDynamicPattern = /* @__PURE__ */ __name(() => {
      const workspaces = fg.globSync(`${path2}*/${this.dispatcherNecessaryFiles.packageJson}`, {
        dot: true
      });
      const jsons = [];
      workspaces.forEach((item, index) => {
        const fields = {
          path: item.replace("package.json", ""),
          ...JSON.parse(readFileSync(workspaces[index], "utf8"))
        };
        jsons.push(fields);
      });
      return jsons;
    }, "resolveDynamicPattern");
    const resolveStaticWorkspaces = /* @__PURE__ */ __name(() => {
      const workspacePackageJsonPath = _FileManager.joinPaths(path2, this.dispatcherNecessaryFiles.packageJson);
      if (!existsSync(workspacePackageJsonPath)) {
        console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] Workspace '${workspace}' has no package.json on disk; skipped.`);
        return [];
      }
      const fields = {
        path: path2,
        ...JSON.parse(readFileSync(workspacePackageJsonPath, "utf8"))
      };
      return [
        fields
      ];
    }, "resolveStaticWorkspaces");
    return {
      resolveDynamicPattern,
      resolveStaticWorkspaces,
      resolveRoot
    };
  }
  createFolderIfAbsent(folderPath) {
    if (!existsSync(folderPath)) {
      mkdirSync(folderPath, {
        recursive: true
      });
    }
  }
  createFileIfAbsent(filePath, defaultContent = "") {
    if (!existsSync(filePath)) {
      writeFileSync2(filePath, defaultContent);
    }
  }
  validateDispatcherDependency(dependencies) {
    return dependencies && dependencies["@dxfrontier/cds-ts-dispatcher"] !== void 0;
  }
  appendLineIfAbsent(filePath, line) {
    const content = readFileSync(filePath, "utf8");
    if (!content.includes(line)) {
      appendFileSync(filePath, `
${line}
`);
    }
  }
  updateGitIgnore(filePath) {
    this.appendLineIfAbsent(filePath, this.dispatcherNecessaryFiles.folder);
  }
  updatePackageJsonImports(filePath) {
    if (existsSync(filePath)) {
      const json = JSON.parse(readFileSync(filePath, "utf8"));
      json.imports = json.imports || {};
      if (!json.imports["#dispatcher"]) {
        json.imports["#dispatcher"] = "./@dispatcher/index.js";
        writeFileSync2(filePath, JSON.stringify(json, null, 2));
      }
    }
  }
  /**
  * Adds `./@dispatcher` to the tsconfig `include` list.
  *
  * `tsconfig.json` is JSONC — comments and trailing commas are legal (tsc accepts both) — so the
  * entry is appended through jsonc-parser edit operations that leave the rest of the file
  * (comments, formatting) untouched, instead of a parse → stringify rewrite. A file that cannot be
  * parsed at all is reported and skipped; it must never abort the consumer's install.
  */
  updateTsconfigInclude(filePath) {
    if (!existsSync(filePath)) {
      return;
    }
    const tsconfigContent = readFileSync(filePath, "utf8");
    const errors = [];
    const tsconfig = parseJsonc(tsconfigContent, errors, {
      allowTrailingComma: true
    });
    if (errors.length > 0 || tsconfig === null || typeof tsconfig !== "object") {
      console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] Could not parse ${filePath}; add './@dispatcher' to its "include" list manually.`);
      return;
    }
    const include = Array.isArray(tsconfig.include) ? tsconfig.include : [];
    if (include.includes("./@dispatcher")) {
      return;
    }
    const formatting = {
      formattingOptions: {
        insertSpaces: true,
        tabSize: 2
      }
    };
    const edits = Array.isArray(tsconfig.include) ? modify(tsconfigContent, [
      "include",
      -1
    ], "./@dispatcher", formatting) : modify(tsconfigContent, [
      "include"
    ], [
      "./@dispatcher"
    ], formatting);
    writeFileSync2(filePath, applyEdits(tsconfigContent, edits));
  }
  createOrUpdateConfigFiles(options) {
    this.createFolderIfAbsent(options.dispatcherFolderPath);
    this.createFileIfAbsent(options.envFilePath);
    this.createFileIfAbsent(options.runtimeStubPath, RUNTIME_STUB_CONTENT);
    this.createFileIfAbsent(options.gitignoreFilePath);
    this.updateGitIgnore(options.gitignoreFilePath);
    this.updatePackageJsonImports(options.packageJsonPath);
    this.updateTsconfigInclude(options.tsconfigPath);
  }
  processInstallation(directory) {
    const dispatcherFolderPath = _FileManager.joinPaths(directory, this.dispatcherNecessaryFiles.folder);
    const packageJsonPath = _FileManager.joinPaths(directory, this.dispatcherNecessaryFiles.packageJson);
    const tsconfigPath = _FileManager.joinPaths(directory, this.dispatcherNecessaryFiles.tsConfig);
    const gitignoreFilePath = _FileManager.joinPaths(directory, this.dispatcherNecessaryFiles.gitIgnore);
    const envFilePath = _FileManager.joinPaths(dispatcherFolderPath, this.dispatcherNecessaryFiles.env);
    const runtimeStubPath = _FileManager.joinPaths(dispatcherFolderPath, this.dispatcherNecessaryFiles.runtimeStub);
    this.createOrUpdateConfigFiles({
      dispatcherFolderPath,
      envFilePath,
      runtimeStubPath,
      gitignoreFilePath,
      packageJsonPath,
      tsconfigPath
    });
    this.dispatcherExecutionPath.paths.push({
      executedInstalledPath: directory,
      envFilePath,
      runtimeStubPath,
      dispatcherPath: dispatcherFolderPath
    });
  }
  processRoot() {
    this.processInstallation(this.currentInstallDirectory);
  }
  processWorkspaces() {
    const workspaces = this.getRootPackageJson().getWorkspaces();
    workspaces.forEach((workspace) => {
      const isDynamic = this.isWorkspaceDynamicPattern(workspace);
      const packages = isDynamic ? this.getParsedPackageJson(workspace).resolveDynamicPattern() : this.getParsedPackageJson(workspace).resolveStaticWorkspaces();
      packages.forEach((pkg) => {
        if (this.validateDispatcherDependency(pkg.dependencies)) {
          isDynamic ? this.processInstallation(pkg.path) : this.processInstallation(_FileManager.joinPaths(this.currentInstallDirectory, workspace));
        }
      });
    });
  }
  run() {
    const rootPackageJsonPath = _FileManager.joinPaths(this.currentInstallDirectory, this.dispatcherNecessaryFiles.packageJson);
    if (!existsSync(rootPackageJsonPath)) {
      console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] No package.json found at ${this.currentInstallDirectory}; skipped @dispatcher setup.`);
      return;
    }
    const rootPackageJson = this.getRootPackageJson();
    if (process.env.INIT_CWD === void 0 && rootPackageJson.isDispatcherItself()) {
      console.warn("\u26A0\uFE0F  [cds-ts-dispatcher] INIT_CWD is not set and the current directory is the dispatcher package itself; skipped @dispatcher setup. Re-run from the consumer project root.");
      return;
    }
    if (rootPackageJson.hasWorkspaces()) {
      this.processWorkspaces();
      return;
    }
    this.processRoot();
  }
};

// postinstall/util/ShellCommander.ts
import { sync } from "cross-spawn";
var ShellCommander = class _ShellCommander {
  static {
    __name(this, "ShellCommander");
  }
  // A postinstall must never hang a consumer's `npm install`: a stuck env probe or `cds` CLI is
  // killed after this long and surfaces as a regular failed result instead of blocking forever.
  static EXECUTION_TIMEOUT_MS = 6e4;
  /**
  * Executes a command synchronously and returns a structured, non-throwing result.
  *
  * A postinstall script must never abort a consumer's `npm install`, so instead of throwing
  * this surfaces the exit status, `stdout` and `stderr` for the caller to inspect and decide upon.
  */
  executeCommand(command, args, currentExecutionPath) {
    const result = sync(command, args, {
      encoding: "utf8",
      cwd: currentExecutionPath,
      timeout: _ShellCommander.EXECUTION_TIMEOUT_MS,
      // SIGTERM (the default) can be trapped and ignored by the child, which would turn the
      // timeout into the very hang it exists to prevent; SIGKILL cannot be trapped.
      killSignal: "SIGKILL"
    });
    return {
      status: result.status,
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
      failed: result.error != null || (result.status ?? 1) !== 0,
      errorMessage: result.error?.message
    };
  }
};

// postinstall/util/TypeGenerator.ts
var INDENT = "  ";
var IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
var NEEDS_JSON_QUOTING = /[\u0000-\u001f'\\\u2028\u2029]/;
var MAX_DEPTH = 64;
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
__name(isRecord, "isRecord");
function formatKey(key) {
  if (IDENTIFIER_PATTERN.test(key)) {
    return key;
  }
  if (NEEDS_JSON_QUOTING.test(key)) {
    return JSON.stringify(key);
  }
  return `'${key}'`;
}
__name(formatKey, "formatKey");
function renderMembers(value, indentLevel) {
  const pad = INDENT.repeat(indentLevel);
  return Object.keys(value).map((key) => `${pad}${formatKey(key)}: ${renderType(value[key], indentLevel + 1)};`).join("\n");
}
__name(renderMembers, "renderMembers");
function renderObject(value, indentLevel) {
  if (Object.keys(value).length === 0) {
    return "{}";
  }
  const closingPad = INDENT.repeat(indentLevel - 1);
  return `{
${renderMembers(value, indentLevel)}
${closingPad}}`;
}
__name(renderObject, "renderObject");
function renderArray(value, indentLevel) {
  if (value.length === 0) {
    return "unknown[]";
  }
  const elementTypes = [];
  value.forEach((item) => {
    const type = renderType(item, indentLevel);
    if (!elementTypes.includes(type)) {
      elementTypes.push(type);
    }
  });
  if (elementTypes.length === 1) {
    return `${elementTypes[0]}[]`;
  }
  return `Array<${elementTypes.join(" | ")}>`;
}
__name(renderArray, "renderArray");
function renderType(value, indentLevel) {
  if (indentLevel > MAX_DEPTH) {
    return "unknown";
  }
  if (value === null) {
    return "null";
  }
  switch (typeof value) {
    case "string":
      return "string";
    case "number":
    case "bigint":
      return "number";
    case "boolean":
      return "boolean";
    default:
      break;
  }
  if (Array.isArray(value)) {
    return renderArray(value, indentLevel);
  }
  if (isRecord(value)) {
    return renderObject(value, indentLevel);
  }
  return "unknown";
}
__name(renderType, "renderType");
function generateCdsEnvType(env) {
  if (!isRecord(env) || Object.keys(env).length === 0) {
    return "export interface CDS_ENV {}";
  }
  return `export interface CDS_ENV {
${renderMembers(env, 1)}
}`;
}
__name(generateCdsEnvType, "generateCdsEnvType");

// postinstall/util/EnvGenerator.ts
var EnvGenerator = class {
  static {
    __name(this, "EnvGenerator");
  }
  fileManager;
  shellCommander;
  // Matches CSI color sequences: ESC (0x1b) followed by `[<digits/;>m`, e.g. the `\x1b[32m` that
  // `cds` emits around string values when it renders with colors instead of plain JSON.
  ansiPattern = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");
  // Single-line, dependency-free probe executed by a fresh `node` process inside the consumer
  // project. `require('@sap/cds').env` is a plain object that `JSON.stringify` renders as clean JSON,
  // immune to `GITHUB_ACTIONS`/`FORCE_COLOR` (unlike the CLI, which switches to a colored
  // `util.inspect` dump under CI). The result is written to a file so unrelated stdout noise
  // (plugin banners, deprecation notices) cannot corrupt the payload.
  envProbeScript = `const r=require.resolve('@sap/cds',{paths:[process.cwd()]});require("fs").writeFileSync(process.argv[1],JSON.stringify(require(r).env));`;
  // Temporary transport file for the programmatic probe. It lives inside the already-created
  // `@dispatcher` folder (no `os.tmpdir` dependency) and is removed in a `finally`.
  transportFileName = ".cds-env.tmp.json";
  constructor() {
    this.fileManager = new FileManager();
    this.shellCommander = new ShellCommander();
  }
  /**
  * PRIMARY acquisition path — programmatic, no CLI.
  *
  * Spawns `process.execPath` with `-e` and the probe script, `cwd` set to the consumer project so
  * `require.resolve('@sap/cds')` finds the project's own `@sap/cds`. On success the transport file
  * holds the stringified `cds.env`, which is then `JSON.parse`d as a validation gate.
  */
  acquireEnvProgrammatically(executedInstalledPath, dispatcherPath) {
    const transportFile = FileManager.joinPaths(dispatcherPath, this.transportFileName);
    try {
      const result = this.shellCommander.executeCommand(process.execPath, [
        "-e",
        this.envProbeScript,
        transportFile
      ], executedInstalledPath);
      if (result.failed) {
        const detail = this.compressFailureDetail(result.stderr) || result.errorMessage || "";
        return {
          ok: false,
          reason: `programmatic \`@sap/cds\` env probe failed (exit code ${result.status}). ${detail}`.trim(),
          rawSample: result.stderr || result.stdout
        };
      }
      if (!existsSync2(transportFile)) {
        return {
          ok: false,
          reason: "programmatic `@sap/cds` env probe produced no output.",
          rawSample: result.stdout
        };
      }
      return this.parseEnv(readFileSync2(transportFile, "utf8"), "programmatic `@sap/cds` env probe");
    } finally {
      this.removeTransportFile(transportFile);
    }
  }
  /**
  * FALLBACK acquisition path — the hardened CLI.
  *
  * Runs `cds env get --json`, strips ANSI, extracts the object literal, then `JSON.parse`s it as a
  * validation gate (previously the extracted string reached the type generator unvalidated).
  */
  acquireEnvViaCli(executedInstalledPath) {
    const result = this.getCdsEnvOutput(executedInstalledPath);
    if (result.failed || result.stdout.trim().length === 0) {
      const detail = this.compressFailureDetail(result.stderr) || result.errorMessage || "";
      const reason = result.failed ? `\`cds env get --json\` failed (exit code ${result.status}). ${detail}`.trim() : "`cds env get --json` produced empty output.";
      return {
        ok: false,
        reason,
        rawSample: result.stdout || result.stderr
      };
    }
    const envObject = this.extractEnvObject(result.stdout);
    if (envObject === null) {
      return {
        ok: false,
        reason: "no JSON object could be extracted from `cds env get --json` output.",
        rawSample: result.stdout
      };
    }
    return this.parseEnv(envObject, "`cds env get --json`");
  }
  /**
  * Compresses a child process's stderr into a single informative line for warning messages: a
  * failed `require` dumps a full multiline stack trace, but install logs deserve just the
  * `Error: …` essence. The raw sample shown alongside skip warnings keeps the uncompressed data.
  */
  compressFailureDetail(raw) {
    const lines = raw.trim().split("\n").map((line) => line.trim()).filter(Boolean);
    if (lines.length === 0) {
      return "";
    }
    const errorLine = lines.find((line) => /^\w*Error[:\s]/.test(line));
    return (errorLine ?? lines[0]).slice(0, 300);
  }
  /**
  * Validation gate shared by both acquisition paths: parses the raw payload and reports invalid
  * JSON as a skip reason rather than letting it reach the type generator.
  */
  parseEnv(raw, source) {
    try {
      return {
        ok: true,
        env: JSON.parse(raw)
      };
    } catch (error) {
      return {
        ok: false,
        reason: `${source} returned invalid JSON: ${error.message}`,
        rawSample: raw
      };
    }
  }
  /**
  * Runs `cds env get --json` inside the given project.
  *
  * The explicit `--json` flag is essential: without it `cds` inspects the environment and, when
  * it detects a CI provider (e.g. `GITHUB_ACTIONS`), switches to a colored `util.inspect` rendering
  * (`Config { _context: 'cds', ... }` with ANSI escape codes) instead of plain JSON. That non-JSON,
  * lossy payload is exactly what broke CI installs, and it cannot be recovered by post-processing.
  * Forcing `--json` yields the same clean, complete output on every platform.
  */
  getCdsEnvOutput(path2) {
    return this.shellCommander.executeCommand("cds", [
      "env",
      "get",
      "--json"
    ], path2);
  }
  /**
  * Strips ANSI escape sequences and extracts the JSON object literal, from the first `{` to the
  * last `}`. Acts as a safety net so that any residual decoration around the payload (banners,
  * colors, notices printed by older `cds` versions) never reaches the parser.
  *
  * @returns the sanitized object literal, or `null` when no object literal can be found.
  */
  extractEnvObject(raw) {
    const withoutAnsi = raw.replace(this.ansiPattern, "");
    const start = withoutAnsi.indexOf("{");
    const end = withoutAnsi.lastIndexOf("}");
    if (start === -1 || end === -1 || end < start) {
      return null;
    }
    return withoutAnsi.slice(start, end + 1);
  }
  /**
  * Best-effort removal of the transport file. A leftover temp file must never fail the install.
  */
  removeTransportFile(transportFile) {
    try {
      if (existsSync2(transportFile)) {
        rmSync(transportFile);
      }
    } catch {
    }
  }
  /**
  * Writes `@dispatcher/index.ts`: the header comment plus the `export interface CDS_ENV` produced
  * by the in-house type generator.
  */
  createEnvFile(filePath, env) {
    const fileContent = `// Type definitions for envConfig
${generateCdsEnvType(env)}
`;
    writeFileSync3(filePath, fileContent);
  }
  /**
  * Loudly reports an execution path that could not be processed, then lets the caller continue.
  * The `@dispatcher` folder is a convenience that backs the typed `#dispatcher` import; a failure
  * here must never abort the consumer's `npm install`.
  */
  skipWithWarning(path2, reason, rawSample) {
    console.warn([
      "",
      `\u26A0\uFE0F  [cds-ts-dispatcher] Skipped @dispatcher env generation for: ${path2}`,
      `    Reason: ${reason}`,
      `    Raw output (first 200 chars): ${JSON.stringify(rawSample.slice(0, 200))}`,
      "    The library still works; regenerate later by reinstalling once `@sap/cds` is installed.",
      ""
    ].join("\n"));
  }
  /**
  * Generates the env file for a single execution path using the acquisition ladder:
  * programmatic probe first, hardened CLI as a fallback, skip-with-warning when both fail.
  *
  * @returns `true` when the files were generated, `false` when the path was skipped.
  */
  generateEnvFileForPath(paths) {
    const { executedInstalledPath, envFilePath, runtimeStubPath, dispatcherPath } = paths;
    const primary = this.acquireEnvProgrammatically(executedInstalledPath, dispatcherPath);
    let acquisition;
    if (primary.ok) {
      acquisition = primary;
    } else {
      const fallback = this.acquireEnvViaCli(executedInstalledPath);
      if (!fallback.ok) {
        this.skipWithWarning(executedInstalledPath, `${primary.reason} Fallback: ${fallback.reason}`, fallback.rawSample);
        return false;
      }
      console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] Programmatic @sap/cds env read failed (${primary.reason}) \u2014 used the \`cds env get --json\` fallback instead.`);
      acquisition = fallback;
    }
    this.createEnvFile(envFilePath, acquisition.env);
    writeRuntimeStub(runtimeStubPath);
    return true;
  }
  generateEnvFiles() {
    const { paths } = this.fileManager.dispatcherExecutionPath;
    let generated = 0;
    paths.forEach((path2) => {
      try {
        if (this.generateEnvFileForPath(path2)) {
          generated += 1;
        }
      } catch (error) {
        this.skipWithWarning(path2.executedInstalledPath, `unexpected error: ${error.message}`, "");
      }
    });
    if (paths.length > 0 && generated === 0) {
      console.warn("\u26A0\uFE0F  [cds-ts-dispatcher] No @dispatcher env files could be generated. The library is installed and usable; only the typed `#dispatcher` env import is affected.");
    }
  }
  /**
  * Entry point for the postinstall step.
  *
  * Policy: this never calls `process.exit(1)`. Generating `@dispatcher` type definitions is a
  * convenience, and breaking every consumer's `npm install` on a `cds env` hiccup (the original
  * bug) is disproportionate. Unusable paths are skipped with a loud warning; any unexpected error
  * is caught and reported instead of propagating.
  */
  run() {
    try {
      this.generateEnvFiles();
    } catch (error) {
      console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] Postinstall env generation skipped: ${error.message}`);
    }
  }
};

// postinstall/PostInstall.ts
var PostInstall = class PostInstall2 {
  static {
    __name(this, "PostInstall");
  }
  run() {
    try {
      new EnvGenerator().run();
    } catch (error) {
      console.warn(`\u26A0\uFE0F  [cds-ts-dispatcher] Postinstall skipped: ${error.message}`);
    }
  }
};
new PostInstall().run();
//# sourceMappingURL=PostInstall.mjs.map