import { writeFileSync } from 'fs';

/**
 * Content of `@dispatcher/index.js`, the runtime target of the `#dispatcher` import alias.
 *
 * The generated `index.ts` is types-only, so the alias never needs real runtime exports. The stub
 * is intentionally comment-only — no `module.exports`, no `export {}` — so it parses under both
 * CommonJS and ESM consumers regardless of their package `type`.
 *
 * It lives in its own module because two writers need it: `FileManager` creates the stub while
 * scaffolding (`imports['#dispatcher']` targets it unconditionally, so it must exist even when env
 * acquisition later fails) and `EnvGenerator` rewrites it on every successful generation.
 */
export const RUNTIME_STUB_CONTENT = [
  "// Generated by @dxfrontier/cds-ts-dispatcher — runtime stub for the '#dispatcher' import alias.",
  '// All exports are TypeScript types; see index.ts.',
  '',
].join('\n');

/**
 * (Re)writes the runtime stub. Idempotent — the content is static.
 */
export function writeRuntimeStub(filePath: string): void {
  writeFileSync(filePath, RUNTIME_STUB_CONTENT);
}
