export const Constants = {
  DECORATOR: {
    ENTITY_HANDLER_NAME: 'ENTITY_NAME',
    METHOD_ACCUMULATOR_NAME: 'METHOD_ACCUMULATOR',
    INJECTOR_FIELDS_ACCUMULATOR_NAME: 'INJECTOR_ACCUMULATOR',
    SINGLE_INSTANCE_FLAG_KEY: 'SINGLE_INSTANCE_KEY',
  },
};

export const SRV = 'srv';

export default Constants;
