class Constants {
  public static DECORATOR = {
    ENTITY_HANDLER_NAME: 'ENTITY_NAME',
    METHOD_ACCUMULATOR_NAME: 'METHOD_ACCUMULATOR',
    INJECTOR_FIELDS_ACCUMULATOR_NAME: 'INJECTOR_ACCUMULATOR',
    DRAFT_FLAG_KEY: 'DRAFT_KEY',
  }
}

export default Constants
