name: Tests (unit, e2e)

# This workflow run tests for the @Env decorator in the sample projects but after the PR is closed.
# This is a special case especially when @sap/cds-dk and @sap/cds have major version changes.

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  check_valid_deploy:
    name: Validate deploy conditions
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Proceed valid"

  test-env-decorator:
    name: Test @Env decorator
    needs: check_valid_deploy
    strategy:
      matrix:
        include:
          # Node 24
          - version: 24
            platform: ubuntu-latest
          # Node 22
          - version: 22
            platform: ubuntu-latest
          # Node 22 on other platforms
          - version: 22
            platform: macos-latest
          - version: 22
            platform: windows-2022
          - version: 22
            platform: windows-2025

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm install -g @sap/cds-dk ts-node typescript
          npm install

      - name: Build project
        run: npm run build

      - name: Verify @decorator folder, index.ts file, and content
        run: |
          cd ./test/sample-project/bookshop
          npm install
          cd ../../../
          npm run test:verifier

      - name: Verify @decorator folder, index.ts file, and content in monorepo projects
        run: |
          cd ./test/sample-project/monorepo_bookshop
          npm install
          cd ../../../
          npm run test:verifier:monorepo
